# Generated by Django 4.2.5 on 2023-10-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=800)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=2000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
