# Generated by Django 4.2.5 on 2023-10-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aslapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signs',
            new_name='Sign',
        ),
    ]
